import Head from "next/head";
import Hero from "~/components/Hero";
import NavBar from "~/components/NavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-[#eeeeee] bg-[#222831] min-h-screen w-full flex flex-col items-center">
        <NavBar />
        <Hero />
      </main>
    </>
  );
}
